// -----------------------------------------------------------------------
// <copyright file="UnitData.cs" company="Microsoft">
// TODO: Update copyright text.
// </copyright>
// -----------------------------------------------------------------------

namespace Starcraft2.ReplayParser.Version
{
    using System.Collections.Generic;


    /// <summary>
    /// Provides version dispatch for unit type data
    /// </summary>
    public static class UnitData
    {
        public static UnitType GetUnitType(int typeId, int buildNumber)
        {
            if (UnitTypeData.ContainsKey(buildNumber))
            {
                if (UnitTypeData[buildNumber].ContainsKey(typeId))
                {
                    return UnitTypeData[buildNumber][typeId];
                }
            }
            return UnitType.Unknown;
        }

        static Dictionary<int, Dictionary<int, UnitType>> UnitTypeData = new Dictionary<int, Dictionary<int, UnitType>>()
        {
            {21029, new Dictionary<int, UnitType>()
            {
                {0x1D, UnitType.Colossus},
                {0x1E, UnitType.TechLab},
                {0x1F, UnitType.Reactor},
                {0x21, UnitType.InfestorTerran},
                {0x22, UnitType.BanelingCocoon},
                {0x23, UnitType.Baneling},
                {0x24, UnitType.Mothership},
                {0x25, UnitType.PointDefenseDrone},
                {0x26, UnitType.Changeling},
                {0x27, UnitType.ChangelingZealot},
                {0x28, UnitType.ChangelingMarine},
                {0x29, UnitType.ChangelingMarine},
                {0x2A, UnitType.ChangelingZergling},
                {0x2B, UnitType.ChangelingZergling},
                {0x2D, UnitType.CommandCenter},
                {0x2E, UnitType.SupplyDepot},
                {0x2F, UnitType.Refinery},
                {0x30, UnitType.Barracks},
                {0x31, UnitType.EngineeringBay},
                {0x32, UnitType.MissileTurret},
                {0x33, UnitType.Bunker},
                {0x34, UnitType.SensorTower},
                {0x35, UnitType.GhostAcademy},
                {0x36, UnitType.Factory},
                {0x37, UnitType.Starport},
                {0x39, UnitType.Armory},
                {0x3A, UnitType.FusionCore},
                {0x3B, UnitType.AutoTurret},
                {0x3C, UnitType.SiegeTankSieged},
                {0x3D, UnitType.SiegeTank},
                {0x3E, UnitType.VikingAssault},
                {0x3F, UnitType.VikingFighter},
                {0x40, UnitType.CommandCenterFlying},
                {0x41, UnitType.BarracksTechLab},
                {0x42, UnitType.BarracksReactor},
                {0x43, UnitType.FactoryTechLab},
                {0x44, UnitType.FactoryReactor},
                {0x45, UnitType.StarportTechLab},
                {0x46, UnitType.StarportReactor},
                {0x47, UnitType.FactoryFlying},
                {0x48, UnitType.StarportFlying},
                {0x49, UnitType.SCV},
                {0x4A, UnitType.BarracksFlying},
                {0x4B, UnitType.SupplyDepotLowered},
                {0x4C, UnitType.Marine},
                {0x4D, UnitType.Reaper},
                {0x4E, UnitType.Ghost},
                {0x4F, UnitType.Marauder},
                {0x50, UnitType.Thor},
                {0x51, UnitType.Hellion},
                {0x52, UnitType.Medivac},
                {0x53, UnitType.Banshee},
                {0x54, UnitType.Raven},
                {0x55, UnitType.Battlecruiser},
                {0x57, UnitType.Nexus},
                {0x58, UnitType.Pylon},
                {0x59, UnitType.Assimilator},
                {0x5A, UnitType.Gateway},
                {0x5B, UnitType.Forge},
                {0x5C, UnitType.FleetBeacon},
                {0x5D, UnitType.TwilightCouncil},
                {0x5E, UnitType.PhotonCannon},
                {0x5F, UnitType.Stargate},
                {0x60, UnitType.TemplarArchive},
                {0x61, UnitType.DarkShrine},
                {0x62, UnitType.RoboticsBay},
                {0x63, UnitType.RoboticsFacility},
                {0x64, UnitType.CyberneticsCore},
                {0x65, UnitType.Zealot},
                {0x66, UnitType.Stalker},
                {0x67, UnitType.HighTemplar},
                {0x68, UnitType.DarkTemplar},
                {0x69, UnitType.Sentry},
                {0x6A, UnitType.Phoenix},
                {0x6B, UnitType.Carrier},
                {0x6C, UnitType.VoidRay},
                {0x6D, UnitType.WarpPrism},
                {0x6E, UnitType.Observer},
                {0x6F, UnitType.Immortal},
                {0x70, UnitType.Probe},
                {0x71, UnitType.Interceptor},
                {0x72, UnitType.Hatchery},
                {0x73, UnitType.CreepTumor},
                {0x74, UnitType.Extractor},
                {0x75, UnitType.SpawningPool},
                {0x76, UnitType.EvolutionChamber},
                {0x77, UnitType.HydraliskDen},
                {0x78, UnitType.Spire},
                {0x79, UnitType.UltraliskCavern},
                {0x7A, UnitType.InfestationPit},
                {0x7B, UnitType.NydusNetwork},
                {0x7C, UnitType.BanelingNest},
                {0x7D, UnitType.RoachWarren},
                {0x7E, UnitType.SpineCrawler},
                {0x7F, UnitType.SporeCrawler},
                {0x80, UnitType.Lair},
                {0x81, UnitType.Hive},
                {0x82, UnitType.GreaterSpire},
                {0x83, UnitType.Egg},
                {0x84, UnitType.Drone},
                {0x85, UnitType.Zergling},
                {0x86, UnitType.Overlord},
                {0x87, UnitType.Hydralisk},
                {0x88, UnitType.Mutalisk},
                {0x89, UnitType.Ultralisk},
                {0x8A, UnitType.Roach},
                {0x8B, UnitType.Infestor},
                {0x8C, UnitType.Corruptor},
                {0x8D, UnitType.BroodLordCocoon},
                {0x8E, UnitType.BroodLord},
                {0x8F, UnitType.BanelingBurrowed},
                {0x90, UnitType.DroneBurrowed},
                {0x91, UnitType.HydraliskBurrowed},
                {0x92, UnitType.RoachBurrowed},
                {0x93, UnitType.ZerglingBurrowed},
                {0x94, UnitType.InfestorTerranBurrowed},
                {0x99, UnitType.QueenBurrowed},
                {0x9A, UnitType.Queen},
                {0x9B, UnitType.InfestorBurrowed},
                {0x9C, UnitType.OverlordCocoon},
                {0x9D, UnitType.Overseer},
                {0x9E, UnitType.PlanetaryFortress},
                {0x9F, UnitType.UltraliskBurrowed},
                {0xA0, UnitType.OrbitalCommand},
                {0xA1, UnitType.WarpGate},
                {0xA2, UnitType.OrbitalCommandFlying},
                {0xA3, UnitType.ForceField},
                {0xA4, UnitType.WarpPrismPhasing},
                {0xA5, UnitType.CreepTumorBurrowed},
                {0xA6, UnitType.SpineCrawlerUprooted},
                {0xA7, UnitType.SporeCrawlerUprooted},
                {0xA8, UnitType.Archon},
                {0xA9, UnitType.NydusCanal},
                {0xAB, UnitType.RichMineralField},
                {0xAD, UnitType.XelNagaTower},
                {0xB0, UnitType.InfestedTerransEgg},
                {0xB1, UnitType.Larva},
                {0xB9, UnitType.MULE},
                {0xD0, UnitType.Broodling},
                {0xE4, UnitType.Lyote},
                {0xE5, UnitType.CarrionBird},
                {0xE6, UnitType.Karak},
                {0xE7, UnitType.Karak},
                {0xE8, UnitType.Ursadak},
                {0xE9, UnitType.Ursadak},
                {0xEA, UnitType.Ursadak},
                {0xEB, UnitType.Ursadak},
                {0xEC, UnitType.Ursadak},
                {0xED, UnitType.UtilityBot},
                {0xEE, UnitType.CommentatorBot},
                {0xEF, UnitType.CommentatorBot},
                {0xF0, UnitType.CommentatorBot},
                {0xF1, UnitType.CommentatorBot},
                {0xF2, UnitType.Scantipede},
                {0xF8, UnitType.MineralField},
                {0xF9, UnitType.VespeneGeyser},
                {0xFA, UnitType.SpacePlatformGeyser},
                {0xFB, UnitType.RichVespeneGeyser},
                {0xFC, UnitType.DestructibleDoodad},
                {0xFD, UnitType.DestructibleDoodad},
                {0xFE, UnitType.DestructibleDoodad},
                {0xFF, UnitType.DestructibleDoodad},
                {0x100, UnitType.DestructibleDoodad},
                {0x101, UnitType.DestructibleDoodad},
                {0x102, UnitType.DestructibleDoodad},
                {0x103, UnitType.DestructibleDoodad},
                {0x104, UnitType.DestructibleDoodad},
                {0x105, UnitType.DestructibleDoodad},
                {0x106, UnitType.DestructibleDoodad},
                {0x107, UnitType.DestructibleDoodad},
                {0x108, UnitType.DestructibleDoodad},
                {0x109, UnitType.DestructibleDoodad},
                {0x10A, UnitType.DestructibleDoodad},
                {0x10B, UnitType.DestructibleDoodad},
                {0x10C, UnitType.DestructibleDoodad},
                {0x10D, UnitType.BraxisAlphaDestructible1x1},
                {0x10E, UnitType.BraxisAlphaDestructible2x2},
                {0x10F, UnitType.DestructibleDebris4x4},
                {0x110, UnitType.DestructibleDebris6x6},
                {0x111, UnitType.DestructibleRock2x4Vertical},
                {0x112, UnitType.DestructibleRock2x4Horizontal},
                {0x113, UnitType.DestructibleRock2x6Vertical},
                {0x114, UnitType.DestructibleRock2x6Horizontal},
                {0x115, UnitType.DestructibleRock4x4},
                {0x116, UnitType.DestructibleRock6x6},
                {0x117, UnitType.DestructibleRampDiagonalHugeULBR},
                {0x118, UnitType.DestructibleRampDiagonalHugeBLUR},
                {0x119, UnitType.DestructibleRampVerticalHuge},
                {0x11A, UnitType.DestructibleRampHorizontalHuge},
                {0x11B, UnitType.DestructibleDebrisRampDiagonalHugeULBR},
                {0x11C, UnitType.DestructibleDebrisRampDiagonalHugeBLUR},
                {0x11D, UnitType.MengskStatue},
                {0x11F, UnitType.DestructibleDoodad}
            }}
        };
    }
}
