// -----------------------------------------------------------------------
// <copyright file="UnitData.cs" company="Microsoft">
// TODO: Update copyright text.
// </copyright>
// -----------------------------------------------------------------------

namespace Starcraft2.ReplayParser.Version
{
    using System.Collections.Generic;


    /// <summary>
    /// Provides version dispatch for unit type data
    /// </summary>
    public static class UnitData
    {
        public static UnitType GetUnitType(int typeId, int buildNumber)
        {
            Dictionary<int, UnitType> versionData;
            if (UnitTypeData.TryGetValue(buildNumber, out versionData))
            {
                UnitType value;
                if (versionData.TryGetValue(typeId, out value))
                {
                    return value;
                }
            }
            return UnitType.Unknown;
        }

        public static int GetUnitSubgroupPriority(UnitType unitType)
        {
            int value;
            if (SubgroupData.TryGetValue(unitType, out value))
            {
                return value;
            }
            else
            {
                return 0; // Default SubgroupPriority
            }
        }

        #region UnitTypeData
        /// <summary>
        /// BuildNumber => UnitTypeId => UnitType
        /// </summary>
        static Dictionary<int, Dictionary<int, UnitType>> UnitTypeData = new Dictionary<int, Dictionary<int, UnitType>>()
        {
            {21029, new Dictionary<int, UnitType>()
            {
                {0x1D, UnitType.Colossus},
                {0x1E, UnitType.TechLab},
                {0x1F, UnitType.Reactor},
                {0x21, UnitType.InfestorTerran},
                {0x22, UnitType.BanelingCocoon},
                {0x23, UnitType.Baneling},
                {0x24, UnitType.Mothership},
                {0x25, UnitType.PointDefenseDrone},
                {0x26, UnitType.Changeling},
                {0x27, UnitType.ChangelingZealot},
                {0x28, UnitType.ChangelingMarine},
                {0x29, UnitType.ChangelingMarine},
                {0x2A, UnitType.ChangelingZergling},
                {0x2B, UnitType.ChangelingZergling},
                {0x2D, UnitType.CommandCenter},
                {0x2E, UnitType.SupplyDepot},
                {0x2F, UnitType.Refinery},
                {0x30, UnitType.Barracks},
                {0x31, UnitType.EngineeringBay},
                {0x32, UnitType.MissileTurret},
                {0x33, UnitType.Bunker},
                {0x34, UnitType.SensorTower},
                {0x35, UnitType.GhostAcademy},
                {0x36, UnitType.Factory},
                {0x37, UnitType.Starport},
                {0x39, UnitType.Armory},
                {0x3A, UnitType.FusionCore},
                {0x3B, UnitType.AutoTurret},
                {0x3C, UnitType.SiegeTankSieged},
                {0x3D, UnitType.SiegeTank},
                {0x3E, UnitType.VikingAssault},
                {0x3F, UnitType.VikingFighter},
                {0x40, UnitType.CommandCenterFlying},
                {0x41, UnitType.BarracksTechLab},
                {0x42, UnitType.BarracksReactor},
                {0x43, UnitType.FactoryTechLab},
                {0x44, UnitType.FactoryReactor},
                {0x45, UnitType.StarportTechLab},
                {0x46, UnitType.StarportReactor},
                {0x47, UnitType.FactoryFlying},
                {0x48, UnitType.StarportFlying},
                {0x49, UnitType.SCV},
                {0x4A, UnitType.BarracksFlying},
                {0x4B, UnitType.SupplyDepotLowered},
                {0x4C, UnitType.Marine},
                {0x4D, UnitType.Reaper},
                {0x4E, UnitType.Ghost},
                {0x4F, UnitType.Marauder},
                {0x50, UnitType.Thor},
                {0x51, UnitType.Hellion},
                {0x52, UnitType.Medivac},
                {0x53, UnitType.Banshee},
                {0x54, UnitType.Raven},
                {0x55, UnitType.Battlecruiser},
                {0x57, UnitType.Nexus},
                {0x58, UnitType.Pylon},
                {0x59, UnitType.Assimilator},
                {0x5A, UnitType.Gateway},
                {0x5B, UnitType.Forge},
                {0x5C, UnitType.FleetBeacon},
                {0x5D, UnitType.TwilightCouncil},
                {0x5E, UnitType.PhotonCannon},
                {0x5F, UnitType.Stargate},
                {0x60, UnitType.TemplarArchive},
                {0x61, UnitType.DarkShrine},
                {0x62, UnitType.RoboticsBay},
                {0x63, UnitType.RoboticsFacility},
                {0x64, UnitType.CyberneticsCore},
                {0x65, UnitType.Zealot},
                {0x66, UnitType.Stalker},
                {0x67, UnitType.HighTemplar},
                {0x68, UnitType.DarkTemplar},
                {0x69, UnitType.Sentry},
                {0x6A, UnitType.Phoenix},
                {0x6B, UnitType.Carrier},
                {0x6C, UnitType.VoidRay},
                {0x6D, UnitType.WarpPrism},
                {0x6E, UnitType.Observer},
                {0x6F, UnitType.Immortal},
                {0x70, UnitType.Probe},
                {0x71, UnitType.Interceptor},
                {0x72, UnitType.Hatchery},
                {0x73, UnitType.CreepTumor},
                {0x74, UnitType.Extractor},
                {0x75, UnitType.SpawningPool},
                {0x76, UnitType.EvolutionChamber},
                {0x77, UnitType.HydraliskDen},
                {0x78, UnitType.Spire},
                {0x79, UnitType.UltraliskCavern},
                {0x7A, UnitType.InfestationPit},
                {0x7B, UnitType.NydusNetwork},
                {0x7C, UnitType.BanelingNest},
                {0x7D, UnitType.RoachWarren},
                {0x7E, UnitType.SpineCrawler},
                {0x7F, UnitType.SporeCrawler},
                {0x80, UnitType.Lair},
                {0x81, UnitType.Hive},
                {0x82, UnitType.GreaterSpire},
                {0x83, UnitType.Egg},
                {0x84, UnitType.Drone},
                {0x85, UnitType.Zergling},
                {0x86, UnitType.Overlord},
                {0x87, UnitType.Hydralisk},
                {0x88, UnitType.Mutalisk},
                {0x89, UnitType.Ultralisk},
                {0x8A, UnitType.Roach},
                {0x8B, UnitType.Infestor},
                {0x8C, UnitType.Corruptor},
                {0x8D, UnitType.BroodLordCocoon},
                {0x8E, UnitType.BroodLord},
                {0x8F, UnitType.BanelingBurrowed},
                {0x90, UnitType.DroneBurrowed},
                {0x91, UnitType.HydraliskBurrowed},
                {0x92, UnitType.RoachBurrowed},
                {0x93, UnitType.ZerglingBurrowed},
                {0x94, UnitType.InfestorTerranBurrowed},
                {0x99, UnitType.QueenBurrowed},
                {0x9A, UnitType.Queen},
                {0x9B, UnitType.InfestorBurrowed},
                {0x9C, UnitType.OverlordCocoon},
                {0x9D, UnitType.Overseer},
                {0x9E, UnitType.PlanetaryFortress},
                {0x9F, UnitType.UltraliskBurrowed},
                {0xA0, UnitType.OrbitalCommand},
                {0xA1, UnitType.WarpGate},
                {0xA2, UnitType.OrbitalCommandFlying},
                {0xA3, UnitType.ForceField},
                {0xA4, UnitType.WarpPrismPhasing},
                {0xA5, UnitType.CreepTumorBurrowed},
                {0xA6, UnitType.SpineCrawlerUprooted},
                {0xA7, UnitType.SporeCrawlerUprooted},
                {0xA8, UnitType.Archon},
                {0xA9, UnitType.NydusCanal},
                {0xAB, UnitType.RichMineralField},
                {0xAD, UnitType.XelNagaTower},
                {0xB0, UnitType.InfestedTerransEgg},
                {0xB1, UnitType.Larva},
                {0xB9, UnitType.MULE},
                {0xD0, UnitType.Broodling},
                {0xE4, UnitType.Lyote},
                {0xE5, UnitType.CarrionBird},
                {0xE6, UnitType.Karak},
                {0xE7, UnitType.Karak},
                {0xE8, UnitType.Ursadak},
                {0xE9, UnitType.Ursadak},
                {0xEA, UnitType.Ursadak},
                {0xEB, UnitType.Ursadak},
                {0xEC, UnitType.Ursadak},
                {0xED, UnitType.UtilityBot},
                {0xEE, UnitType.CommentatorBot},
                {0xEF, UnitType.CommentatorBot},
                {0xF0, UnitType.CommentatorBot},
                {0xF1, UnitType.CommentatorBot},
                {0xF2, UnitType.Scantipede},
                {0xF8, UnitType.MineralField},
                {0xF9, UnitType.VespeneGeyser},
                {0xFA, UnitType.SpacePlatformGeyser},
                {0xFB, UnitType.RichVespeneGeyser},
                {0xFC, UnitType.DestructibleDoodad},
                {0xFD, UnitType.DestructibleDoodad},
                {0xFE, UnitType.DestructibleDoodad},
                {0xFF, UnitType.DestructibleDoodad},
                {0x100, UnitType.DestructibleDoodad},
                {0x101, UnitType.DestructibleDoodad},
                {0x102, UnitType.DestructibleDoodad},
                {0x103, UnitType.DestructibleDoodad},
                {0x104, UnitType.DestructibleDoodad},
                {0x105, UnitType.DestructibleDoodad},
                {0x106, UnitType.DestructibleDoodad},
                {0x107, UnitType.DestructibleDoodad},
                {0x108, UnitType.DestructibleDoodad},
                {0x109, UnitType.DestructibleDoodad},
                {0x10A, UnitType.DestructibleDoodad},
                {0x10B, UnitType.DestructibleDoodad},
                {0x10C, UnitType.DestructibleDoodad},
                {0x10D, UnitType.BraxisAlphaDestructible1x1},
                {0x10E, UnitType.BraxisAlphaDestructible2x2},
                {0x10F, UnitType.DestructibleDebris4x4},
                {0x110, UnitType.DestructibleDebris6x6},
                {0x111, UnitType.DestructibleRock2x4Vertical},
                {0x112, UnitType.DestructibleRock2x4Horizontal},
                {0x113, UnitType.DestructibleRock2x6Vertical},
                {0x114, UnitType.DestructibleRock2x6Horizontal},
                {0x115, UnitType.DestructibleRock4x4},
                {0x116, UnitType.DestructibleRock6x6},
                {0x117, UnitType.DestructibleRampDiagonalHugeULBR},
                {0x118, UnitType.DestructibleRampDiagonalHugeBLUR},
                {0x119, UnitType.DestructibleRampVerticalHuge},
                {0x11A, UnitType.DestructibleRampHorizontalHuge},
                {0x11B, UnitType.DestructibleDebrisRampDiagonalHugeULBR},
                {0x11C, UnitType.DestructibleDebrisRampDiagonalHugeBLUR},
                {0x11D, UnitType.MengskStatue},
                {0x11F, UnitType.DestructibleDoodad}
            }}
        };
        #endregion
        #region SubgroupData
        /// <summary>
        /// Higher priorities mean lower wireframe indices (descending); unit
        /// type id is used as a tie-breaker, and then unit id, both ascending.
        /// </summary>
        static Dictionary<UnitType, int> SubgroupData = new Dictionary<UnitType, int>
        {
            // Neutral units
            {UnitType.MineralField, 1},
            {UnitType.RichMineralField, 1},
            {UnitType.VespeneGeyser, 2},
            {UnitType.SpacePlatformGeyser, 2},
            {UnitType.RichVespeneGeyser, 2},
            // Neutral units - Critters
            {UnitType.Lyote, 48},
            {UnitType.CarrionBird, 48},
            {UnitType.Karak, 48},
            {UnitType.Ursadak, 48},
            {UnitType.UtilityBot, 48},
            {UnitType.CommentatorBot, 48},
            {UnitType.Scantipede, 48},

            // Terran units
            {UnitType.SCV, 6},
            {UnitType.MULE, 5},
            {UnitType.Marine, 15},
            {UnitType.Marauder, 14},
            {UnitType.Reaper, 7},
            {UnitType.Ghost, 18},
            {UnitType.SiegeTank, 13},
            {UnitType.SiegeTankSieged, 13},
            {UnitType.Thor, 10},
            {UnitType.Hellion, 8},
            {UnitType.Medivac, 9},
            {UnitType.Banshee, 11},
            {UnitType.VikingFighter, 12},
            {UnitType.VikingAssault, 12},
            {UnitType.Raven, 19},
            {UnitType.Battlecruiser, 16},

            // Protoss units
            {UnitType.Probe, 3},
            {UnitType.Zealot, 5},
            {UnitType.Stalker, 11},
            {UnitType.Sentry, 16},
            {UnitType.HighTemplar, 17},
            {UnitType.DarkTemplar, 6},
            {UnitType.Archon, 8},
            {UnitType.Immortal, 7},
            {UnitType.Observer, 4},
            {UnitType.WarpPrism, 14},
            {UnitType.WarpPrismPhasing, 13},
            {UnitType.Colossus, 10},
            {UnitType.Phoenix, 15},
            {UnitType.VoidRay, 9},
            {UnitType.Mothership, 18},
            {UnitType.Carrier, 12},
            {UnitType.Interceptor, 19},

            // Zerg units
            {UnitType.Larva, 3},
            {UnitType.Egg, 1},
            {UnitType.Drone, 4},
            {UnitType.DroneBurrowed, 4},
            {UnitType.Queen, 21},
            {UnitType.QueenBurrowed, 20},
            {UnitType.Zergling, 8},
            {UnitType.ZerglingBurrowed, 8},
            {UnitType.BanelingCocoon, 1},
            {UnitType.Baneling, 16},
            {UnitType.BanelingBurrowed, 16},
            {UnitType.Roach, 15},
            {UnitType.RoachBurrowed, 15},
            {UnitType.Overlord, 10},
            {UnitType.OverlordCocoon, 1},
            {UnitType.Overseer, 11},
            {UnitType.Changeling, 5},
            {UnitType.ChangelingZealot, 5},
            {UnitType.ChangelingMarine, 15},
            {UnitType.ChangelingZergling, 8},
            {UnitType.Hydralisk, 9},
            {UnitType.HydraliskBurrowed, 9},
            {UnitType.Mutalisk, 13},
            {UnitType.Infestor, 19},
            {UnitType.InfestorBurrowed, 19},
            {UnitType.InfestorTerran, 6},
            {UnitType.InfestorTerranBurrowed, 6},
            {UnitType.Corruptor, 17},
            {UnitType.BroodLordCocoon, 1},
            {UnitType.BroodLord, 14},
            {UnitType.Broodling, 14},
            {UnitType.Ultralisk, 12},
            {UnitType.UltraliskBurrowed, 12},

            // Terran buildings
            {UnitType.CommandCenter, 3},
            {UnitType.CommandCenterFlying, 3},
            {UnitType.OrbitalCommand, 4},
            {UnitType.OrbitalCommandFlying, 4},
            {UnitType.PlanetaryFortress, 3},
            {UnitType.SupplyDepot, 3},
            {UnitType.SupplyDepotLowered, 3},
            {UnitType.Refinery, 3},
            {UnitType.Barracks, 3},
            {UnitType.BarracksFlying, 3},
            {UnitType.Factory, 3},
            {UnitType.FactoryFlying, 3},
            {UnitType.Starport, 3},
            {UnitType.StarportFlying, 3},
            {UnitType.TechLab, 2},
            {UnitType.BarracksTechLab, 2},
            {UnitType.FactoryTechLab, 2},
            {UnitType.StarportTechLab, 2},
            {UnitType.Reactor, 1},
            {UnitType.BarracksReactor, 1},
            {UnitType.FactoryReactor, 1},
            {UnitType.StarportReactor, 1},
            {UnitType.Bunker, 3},
            {UnitType.MissileTurret, 3},
            {UnitType.SensorTower, 3},
            {UnitType.GhostAcademy, 3},
            {UnitType.EngineeringBay, 3},
            {UnitType.Armory, 3},
            {UnitType.FusionCore, 3},
            {UnitType.AutoTurret, 2},
            {UnitType.PointDefenseDrone, 6},

            // Protoss buildings
            {UnitType.Nexus, 2},
            {UnitType.Pylon, 2},
            {UnitType.Assimilator, 2},
            {UnitType.Gateway, 2},
            {UnitType.Forge, 2},
            {UnitType.FleetBeacon, 2},
            {UnitType.TwilightCouncil, 2},
            {UnitType.PhotonCannon, 2},
            {UnitType.Stargate, 2},
            {UnitType.TemplarArchive, 2},
            {UnitType.DarkShrine, 2},
            {UnitType.RoboticsBay, 2},
            {UnitType.RoboticsFacility, 2},
            {UnitType.CyberneticsCore, 2},
            {UnitType.WarpGate, 3},
            {UnitType.ForceField, 31},

            // Zerg buildings
            {UnitType.Hatchery, 2},
            {UnitType.Lair, 2},
            {UnitType.Hive, 2},
            {UnitType.Extractor, 2},
            {UnitType.CreepTumor, 2},
            {UnitType.CreepTumorBurrowed, 2},
            {UnitType.EvolutionChamber, 2},
            {UnitType.SpawningPool, 2},
            {UnitType.BanelingNest, 2},
            {UnitType.RoachWarren, 2},
            {UnitType.HydraliskDen, 2},
            {UnitType.Spire, 2},
            {UnitType.InfestationPit, 2},
            {UnitType.NydusNetwork, 2},
            {UnitType.NydusCanal, 2},
            {UnitType.UltraliskCavern, 2},
            {UnitType.SpineCrawler, 2},
            {UnitType.SpineCrawlerUprooted, 3},
            {UnitType.SporeCrawler, 2},
            {UnitType.SporeCrawlerUprooted, 3},
            {UnitType.GreaterSpire, 2}
        };
        #endregion
    }
}
